### ISSUE TITLE
dependency name change (from docker/spdystream  to moby/spdystream)

### ISSUE THREAD

**Issue by dlsgusrn7577** [kubernetes/apimachinery#115]
Dear  apimachinery team, 

I am sure you guys are aware of the recent update for https://github.com/moby/spdystream, which switched the name from docker to moby.
Do you guys have any plan for updating https://github.com/kubernetes/apimachinery/blob/master/go.mod for the corresponding dependency? 
Thanks!

**Comment by liggitt** [comment]
done in https://github.com/kubernetes/kubernetes/pull/98565, will be in v0.21.0 of this repo

**Comment by dlsgusrn7577** [comment]
@liggitt Thanks for the quick update!
Is there any timeline on this?

**Comment by liggitt** [comment]
It will be released as part of kubernetes v1.21, schedule at https://github.com/kubernetes/sig-release/tree/master/releases/release-1.21#tldr

it is already published to master of this repo (https://github.com/kubernetes/apimachinery/blob/master/go.mod#L21) but not conveniently consumable yet because it's not on a release tag yet

**Comment by dlsgusrn7577** [comment]
I see. Thank you very much for the update!
