### ISSUE TITLE
BSD License file is missing for thirdparty json and reflect packages

### ISSUE THREAD

**Issue by jayasheelankumar** [kubernetes/apimachinery#126]
The following line in the fields.go talk about BSD style LICENSE file. But, I do not see the BSD License file in the project.

https://github.com/kubernetes/apimachinery/blob/a653093b52fe5b03c2ad0e60edb3c3e648cc705c/third_party/forked/golang/json/fields.go#L2

Can you please help me understand the reason why the BSD file missing? Is this BSD license file referring to golang/json package's BSD file?

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/tree/master/LICENSES/third_party/forked/golang

**Comment by kswartz26** [comment]
Actually, I would like to request this be reopened. According to the terms of the license, you need to include a copy of it with the code. ("Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.") Technically, apimachinery is not complying with the terms because they are not doing so, which is forcing other companies that distribute this code to add it themselves to avoid possible infringement.

Can the maintainers of this project please add that license to this project in the third_party/forked/golang directory, for completeness?

**Comment by liggitt** [comment]
I would tend to agree... opened https://github.com/kubernetes/kubernetes/pull/104279

**Comment by liggitt** [comment]
https://github.com/kubernetes/apimachinery/blob/master/third_party/forked/golang/LICENSE now exists and will be included in v0.23+ tags
